### ISSUE TITLE
Link to the online version of my portfolio app

### ISSUE THREAD

**Issue by RiyaBulia12** [RiyaBulia12/Portfolio#7]
# [Please visit my Portfolio here](https://riyabulia12.github.io/Portfolio/)

**Comment by topeogunleye** [comment]
Hi @RiyaBulia12, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ⚠️

   - You have submitted a Github issue instead of a Pull Request. Kindly update your Github README file with your deployed website link, then submit a PR with changes or a link to your README file that includes a link to the online version of the app.

## Gitflow Not Used ⚠️

- Pull request is to be made from the feature branch into the dev branch, not the main branch.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

>Invalid Code Review Request **does not count** into the code reviews limit.

**Comment by RiyaBulia12** [comment]
I am sure you must be correct and I also thought the same but the Project instruction states that if we have already deployed the app with the updated online version link in the Readme file then we have to open an issue. Please let me know if my understanding is not correct here. 

I am adding the Project Instruction here for your reference:
**_"If by any chance you have deployed your app earlier, open an issue with a link to the online version of your app. Otherwise, submit a link to the PR with changes required for the deploy."_**

Also, here is the link for the project description [https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/5_deploy.md]

**Comment by omarsalem7** [comment]
Hi @RiyaBulia12 😊, 
# STATUS: APPROVED! 🥇 💯 

![giphy](https://media.giphy.com/media/n5VaQoW39Z9S0/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 🚀 
Congratulations! 🎉 

## Highlights
✅ Project has met all the technical aspects you needed for this project. Keep rocking! 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by topeogunleye** [comment]
> Hello [topeogunleye](https://github.com/topeogunleye),
> 
> I am sure you must be correct and I also thought the same but the Project instruction states that if we have already deployed the app with the updated online version link in the Readme file then we have to open an issue. Please let me know if my understanding is not correct here.
> 
> I am adding the Project Instruction here for your reference: **_"If by any chance you have deployed your app earlier, open an issue with a link to the online version of your app. Otherwise, submit a link to the PR with changes required for the deploy."_**
> 
> Also, here is the link for the project description [https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/5_deploy.md]

Thank you so much for informing me of this. you're right @RiyaBulia12 :smile:
